### ISSUE TITLE
Fedora 33 failed to run again

### ISSUE THREAD

**Issue by mesb1** [Cygn/pulseaudio-dlna#15]
Hi.

After some updates looks like it is failed to run with next error:

/usr/bin/pulseaudio-dlna
Traceback (most recent call last):
  File "/usr/bin/pulseaudio-dlna", line 33, in <module>
    sys.exit(load_entry_point('pulseaudio-dlna==0.6.1', 'console_scripts', 'pulseaudio-dlna')())
  File "/usr/bin/pulseaudio-dlna", line 25, in importlib_load_entry_point
    return next(matches).load()`

**Comment by Cygn** [comment]
Hi there,
I had this one and it gave me some head ache to track down. 
Long story short, that's because there are multiple versions of pulseaudio-dlna in your python path - either (1) from a previous manual install or maybe  (2) rpm doesn't clean up the previous one properly when updating (I'm looking into it). 
The most straightforward way to go ATM is to uninstall the pulseaudio-dlna.rpm (rpm -ev); manually remove all pulseaudio-dlna files and dirs from under /usr/lib/python3.9/site-packages ; then reinstall the rpm.  
Let  me also know pls if you're case (1) or (2).

**Comment by Cygn** [comment]
Probably fixed in 0.6.1-5.

**Comment by mesb1** [comment]
Not sure my case is 1:
# rpm -aq | grep pulseaudio-dlna
pulseaudio-dlna-0.6.1-2.noarch
# find / -iname pulseaudio-dlna
/usr/bin/pulseaudio-dlna

It was clean install of fedora 33 and usual updates from time to time via gui or dnf update.
The only software was installed not long ago was avidemux.

**Comment by Cygn** [comment]
I've pushed a new package to copr which removes left-overs from previous installs. That should fix it.

**Comment by mesb1** [comment]
Ok, i will update it and check is it ok or not.

P.S. I have heard sooner or later fedora will go for a pipewire, do you researched is there any worries about dlna stream feature?

**Comment by mesb1** [comment]
Looks like it doesn't help.

pulseaudio-dlna 
Traceback (most recent call last):
  File "/usr/bin/pulseaudio-dlna", line 33, in <module>
    sys.exit(load_entry_point('pulseaudio-dlna==0.6.1', 'console_scripts', 'pulseaudio-dlna')())
  File "/usr/bin/pulseaudio-dlna", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration

**Comment by Cygn** [comment]
hmmm. Can you pls uninstall the rpm and post me the output of 
`ls /usr/lib/python3.*/site-packages/pulse*` ?
and 
`ls ~/.local/lib/python3.*/site-packages/pulse*` ?

**Comment by Cygn** [comment]
> P.S. I have heard sooner or later fedora will go for a pipewire, do you researched is there any worries about dlna stream feature?

Not looked into it more than that, but pipewire should keep pulseaudio compatibility - so I hope it'll work out.

**Comment by mesb1** [comment]
> 
> 
> hmmm. Can you pls uninstall the rpm and post me the output of
> `ls /usr/lib/python3.*/site-packages/pulse*` ?
> and
> `ls ~/.local/lib/python3.*/site-packages/pulse*` ?


Removed:
libid3tag-0.15.1b-33.fc33.x86_64                          
opusfile-0.12-2.fc33.x86_64
pulseaudio-dlna-0.6.1-5.noarch                            
python3-casttube-0.2.1-1.fc33.noarch
python3-chromecast-7.5.1-1.fc33.noarch                    
python3-docopt-0.6.2-18.fc33.noarch
python3-ifaddr-0.1.7-2.fc33.noarch                        
python3-netifaces-0.10.6-12.fc33.x86_64
python3-notify2-0.3.1-9.fc33.noarch                       
python3-protobuf-3.12.4-1.fc33.noarch
python3-psutil-5.7.2-2.fc33.x86_64                        
python3-pyroute2-0.5.6-4.fc33.noarch
python3-setproctitle-1.1.10-19.fc33.x86_64                
python3-zeroconf-0.28.6-1.fc33.noarch
sox-14.4.2.0-29.fc33.x86_64                               
vorbis-tools-1:1.4.0-35.fc33.x86_64

===

`# ls /usr/lib/python3.*/site-packages/pulse*`
/usr/lib/python3.8/site-packages/pulseaudio_dlna:
encoders  images  plugins  __pycache__  utils

/usr/lib/python3.8/site-packages/pulseaudio_dlna-0.6.0-py3.8.egg-info:

/usr/lib/python3.9/site-packages/pulseaudio_dlna-0.6.0-py3.9.egg-info:

===
`[root@turtle ~]# ls ~/.local/lib/python3.*/site-packages/pulse*`
ls: cannot access '/root/.local/lib/python3.*/site-packages/pulse*': No such file or directory

`[user1@turtle ~]$ ls ~/.local/lib/python3.*/site-packages/pulse*`
ls: cannot access '/home/user1/.local/lib/python3.*/site-packages/pulse*': No such file or directory

**Comment by Cygn** [comment]
> 
> `# ls /usr/lib/python3.*/site-packages/pulse*`
> /usr/lib/python3.8/site-packages/pulseaudio_dlna:
> encoders images plugins **pycache** utils
> 
> /usr/lib/python3.8/site-packages/pulseaudio_dlna-0.6.0-py3.8.egg-info:
> 
> /usr/lib/python3.9/site-packages/pulseaudio_dlna-0.6.0-py3.9.egg-info:
> 

Those are orphans from a previous install. rm -rf these then reinstall.

**Comment by mesb1** [comment]
You are awesome. Everything works fine now.
Thanks.

**Comment by Cygn** [comment]
:-)
