### ISSUE TITLE
Build fails due to missing manual file

### ISSUE THREAD

**Issue by jejo86** [Cygn/pulseaudio-dlna#21]
Building version 0.6.1 fails with `error: can't copy 'man/pulseaudio-dlna.1.gz': doesn't exist or not a regular file`.

There is actually only a file `man/pulseaudio-dlna.1`. Gzipping it and rebuilding solves the problem

**Comment by Cygn** [comment]
Strange, which branch are you building? Master is not supposed to work for rpm, and python3-rpm auto-builds fine from copr. 
By the way, makefile is already supposed to add the gz'd man page, but I don't use it anymore, it's there from masmu's debian build process for historical reasons. Anyway, gz'd manpages are in all branches, so I don't know how you coe to miss it.

Oh, don't use setup.py ... --format=rpm - use rpmbuild with the .spec in python3-rpm.

**Comment by jejo86** [comment]
I downloaded release [0.6.1](https://github.com/Cygn/pulseaudio-dlna/archive/0.6.1.tar.gz), which is missing the aforementioned file.

I am using a Debian (Linux Mint 20.1) so I have no use for RPMs. I built the code running the following commands:
```
sudo apt install python3-pychromecast python3-setuptools python3-pip python3-docopt python3-chardet python3-gi python3-dbus python3-docopt python3-requests python3-setproctitle python3-protobuf python3-lxml python3-netifaces python3-zeroconf python3-urllib3 python3-psutil python3-pyroute2 python3-notify2 python3-distutils sox vorbis-tools lame flac opus-tools ffmpeg
wget https://github.com/Cygn/pulseaudio-dlna/archive/0.6.1.tar.gz
tar xvzf 0.6.1.tar.gz -C pulseaudio-dlna

// Create missing gzipped manual
tar cvzf man/pulseaudio-dlna.1.gz man/pulseaudio-dlna.1

cd pulseaudio-dlna
python3 -m pip install --user .
```
