### ISSUE TITLE
ubuntu 20.04cannot find chromecast audio

### ISSUE THREAD

**Issue by github-germ** [Cygn/pulseaudio-dlna#34]
How best to debug and isolate why no devices are found on ubuntu 20.04 although seen in iOS? Thanks!

**Comment by Cygn** [comment]
First test [this](https://pythonrepo.com/repo/home-assistant-libs-pychromecast#how-to-use) to see of pychromecast sees your devices. 
Beware that pychromecast >= 10 does not yet work with pulseaudio-dlna. So if you installed with pip you may have this too recent version.

**Comment by github-germ** [comment]
@Cygn -- Really appreciate your help. I do see my chromecast on iOS and see its IP on the same network as this Ubuntu 20.04 host and do get ping echo replies.

What would you suggest next?
```
$ python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> import pychromecast
>>> pychromecast.__version__
'0.7.6'
>>> services, browser = pychromecast.discovery.discover_chromecasts()
>>> pychromecast.discovery.stop_discovery(browser)
>>> chromecasts, browser = pychromecast.get_listed_chromecasts(friendly_names=["Living Room Stereo"])
>>> len(chromecasts)
0
>>> chromecasts, browser = pychromecast.get_listed_chromecasts()
>>> len(chromecasts)
0
>>> 
```

**Comment by Cygn** [comment]
It looks like pychromecast does not pick up your device, so nothing can be done form pulseaudio-dlna side. 
Maybe see [this](https://github.com/home-assistant-libs/pychromecast/pull/581) and try get_chromecasts() instead of get_listed_chromecasts() if it appears?

**Comment by github-germ** [comment]
Thanks again. `get_chromecasts()` not seeing the device, best I can tell:
```
>>> import time
>>> import pychromecast
>>> services, browser = pychromecast.discovery.discover_chromecasts()
>>> chromecasts, browser = pychromecast.get_chromecasts()
>>> chromecasts
[]
>>> 
```

**Comment by Cygn** [comment]
Well, try with a more recent pychromecast to check, but in any case apparently the issue is not from pulseaudio-dlna and you need to take it there.

**Comment by github-germ** [comment]
One more check before I go post on  https://github.com/home-assistant-libs/pychromecast

Confirming that you believe this should work with `pychromecast < 10.*` ?

...Details...
* It seems like the most recent `pychromecast < 10.*` version is `9.4.0` which sets `__version__` to `0.7.6` (see https://github.com/home-assistant-libs/pychromecast/blob/9.4.0/pychromecast/__init__.py#L33).
* So both`9.4.0` and their latest `10.2.3`never reveal any device.
