### ISSUE TITLE
openSUSE Tumbleweed - Very large buffer delay of 25 seconds

### ISSUE THREAD

**Issue by ryan-ronnander** [Cygn/pulseaudio-dlna#37]
Everything appears in working order, but there is a large ~25 second buffering delay present when routing audio to pulseaudio-dlna.

edit: When a song ends it will stop playback 25 seconds early as well. I did not notice originally as I had a playlist of songs queued up.

**Comment by Cygn** [comment]
The delay issue has been long discussed [upstream](https://github.com/masmu/pulseaudio-dlna), with no clear solutions. It depends on the encoder you choose among other factors. I get myself best results with opus, but not all devices are compatible.
