### ISSUE TITLE
Centos 7 RPM

### ISSUE THREAD

**Issue by avocadio** [Cygn/pulseaudio-dlna#4]
I've noticed that the last working build was done a long time, probably due to the some new requirements. 
https://copr-be.cloud.fedoraproject.org/results/cygn/pulseaudio-dlna/epel-7-x86_64/build-00817368.log

Do you still have the spec file or RPM somewhere for centos7?

Thanks in advance

**Comment by Cygn** [comment]
That's the last one working on EPEL7 bcz the dev has switched to py3 at that point. 
I think I've got the .src.rpm somewhere at least - needs a bit of digging.

**Comment by avocadio** [comment]
That would be great :)

**Comment by Cygn** [comment]
Here it is :)
[pulseaudio-dlna-0.5.2.git20171120-3.src.zip](https://github.com/Cygn/pulseaudio-dlna/files/4672466/pulseaudio-dlna-0.5.2.git20171120-3.src.zip)

**Comment by avocadio** [comment]
Thank you
