### ISSUE TITLE
Ubuntu 20.04 apt-add-repository error

### ISSUE THREAD

**Issue by walkawayy** [Cygn/pulseaudio-dlna#40]
When I run `sudo apt-add-repository ppa:qos/pulseaudio-dlna`, I get an error:
```
Err:8 http://ppa.launchpad.net/qos/pulseaudio-dlna/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
```

I recently updated to 20.04, so I'm not sure if I did a step wrong.

**Comment by Cygn** [comment]
Sorry, you have to take this to ubuntu package maintainers - not related to here.
