### ISSUE TITLE
can't update to 0.6.5-1 on Fedora 35 

### ISSUE THREAD

**Issue by tomerrr** [Cygn/pulseaudio-dlna#43]
when trying to update package on Fedora 35 I get
```
Problem 1: cannot install the best update candidate for package python3-chromecast-9.3.1-1.fc35.noarch
  - nothing provides python3.10dist(protobuf) >= 3.19.1 needed by python3-chromecast-10.3.0-2.noarch
 Problem 2: package pulseaudio-dlna-0.6.5-1.noarch requires python3.10dist(pychromecast) >= 10, but none of the providers can be installed
  - cannot install the best update candidate for package pulseaudio-dlna-0.6.4-1.noarch
  - nothing provides python3.10dist(protobuf) >= 3.19.1 needed by python3-chromecast-10.3.0-2.noarch

```
Fedora is fully updated with these protobuf packages installed:
protobuf-c-1.4.0-1.fc35.x86_64
protobuf-3.14.0-7.fc35.x86_64
protobuf-lite-3.14.0-7.fc35.x86_64
python3-protobuf-3.14.0-7.fc35.noarch

also, pip shows
$ pip list | grep protobuf
protobuf           3.19.4

_Originally posted by @tomerrr in https://github.com/Cygn/pulseaudio-dlna/issues/39#issuecomment-1073286795_

**Comment by Cygn** [comment]
I've rebuilt pychromecast 10.3 with protobuf >= 3.14 instead of 3.19 - it should install now but I really don't know if it'll break something :-/ 
Let me know.

**Comment by Cygn** [comment]
well it does break indeed. `pip install --user protobuf==3.19.1  ` is needed to make it work.

**Comment by tomerrr** [comment]
that seem to fix it. thanks
