### ISSUE TITLE
 The device "Audiolab (DLNA)" failed to play! (500) - "Audiolab (DLNA)" : The action "SetAVTransportURI" is not supported!

### ISSUE THREAD

**Issue by themainliner** [Cygn/pulseaudio-dlna#47]
I used to stream well to the Audiolab (6000A Play), however, I rebuilt Debian and reinstall pulseaudio-dlna and then hit this brick wall. I've been trying multiple fixes and installing many packages. I am yet to hit on any combination that works.

I did my due diligence and Googled this error verbatim and SetAVTransportURI however I've drawn a blank, so against my better judgement I'm asking what does this mean and how can I fix it? I've tested the Debian repo version, 0.6.3 and the latest 0.6.5-1 version...they all have the same issue. I even reinstalled antiX Linux and started from scratch. 

It might be helpful to note that I've also had the same result in Manjaro, elementary and Fedora 35...

Any help, pointers, info...most gratefully received.

**Comment by themainliner** [comment]
I guess dead project is dead. Damn shame as this was worthwhile and useful.

**Comment by Cygn** [comment]
This branch does not work on pipewire without fidgeting. You may try https://github.com/EvTheFuture/pulseaudio-dlna/tree/testing_with_pipewire to see if this works for you.

**Comment by ofl1** [comment]
The question remains whether the error described has something to do with PipeWire. Under https://github.com/peter-nebe/pulseaudio-dlna someone fought with another device, but the same error. He was apparently able to solve it for his device.
