### ISSUE TITLE
Master branch states version 0.6.4 although latest Release is version 0.6.5

### ISSUE THREAD

**Issue by stsichler** [Cygn/pulseaudio-dlna#52]
Hi,
I just cloned your repo and I'm wondering why `pulseaudio-dlna.spec` and `setup.py` still states a version 0.6.4 meanwhile there is a published release 0.6.5 from you.
Did you perhaps forget to push your most recent commit(s) to GitHub ?

**Comment by Cygn** [comment]
Hello
I release from python3-rpm branch as that's what fedora COPR tracks, and the build system (tito) handles the versioning. 
But you're right, its confusing for people, I'll sync those.
