### ISSUE TITLE
errors with pychromecast version 7.5.1 on fedora

### ISSUE THREAD

**Issue by mfdgroot** [Cygn/pulseaudio-dlna#8]
Fedora 33 ships with pychromecast 7.5.1 which breaks pulseaudio-dlna on copr.
The error thrown is:
`AttributeError: 'Chromecast' object has no attribute 'host'`
This comes from new functionality in pychromecast that defines a socket_client object.
While fixing this, there's also an error where the chromecast object exists but is not connected.
I'll post a pull request with both errors fixed that works on Fedora 33 (and is not tested anywhere else).

**Comment by Cygn** [comment]
merged
